# Generated by Django 2.1.5 on 2020-04-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.TextField()),
                ('pid', models.IntegerField()),
                ('uid', models.IntegerField()),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('tag', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Disscussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '讨论',
                'verbose_name_plural': '讨论',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rid', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.TextField()),
                ('uid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delete', models.BooleanField()),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('name', models.TextField()),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name': '分数',
                'verbose_name_plural': '分数',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('carry', models.TextField()),
                ('year', models.TextField()),
                ('introduction', models.TextField()),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
        ),
    ]
